#!/usr/bin/env python3
"""Source-freshness watchdog for a DrugRadar data release.

WHY THIS EXISTS
  A refresh can succeed in every technical sense — HTTP 200, parser happy,
  every gate green — while one of the regulatory sources behind it quietly
  stopped moving. The nightly job then publishes "today's" release on top of
  last week's EMA table or a two-week-old openFDA dataset, and the app says
  "updated today" because the PIPELINE ran today. The release gates
  (validate-release.py) catch regressions of OUR files; this script asks the
  other question: how old is the DATA inside each upstream source, and is that
  within the cadence that source normally keeps?

  It records, per source, the SOURCE-PROVIDED watermark (EMA's report date,
  openFDA's meta.last_updated, the EMA document list's timestamp …) next to
  our own download time, compares both with the previous run's watermarks, and
  grades every source:

    OK      data as fresh as that source's cadence allows
    STALE   the source is alive but behind (or our copy of it is) — the release
            is still RIGHT, only older than it should be; a warning, not a stop
    FAILED  publishing would be WRONG: a watermark moved backwards, a count
            collapsed, a ledger is unreadable — the job must stop before the
            commit/deploy so the previous release stays live

  A stale source is more dangerous than a failed job: a failed job sends a
  mail, a stale source keeps serving yesterday's regulatory state. So STALE is
  always written into the release (release.json → freshness), where the app
  shows "EU data through <date> · US approvals through <date>" instead of a
  misleading "updated today".

SOURCES (what we read, where the watermark comes from, expected cadence)
  ema_medicines_report   EMA medicines report xlsx — report date inside the
                         file (ema-medicines.json.generated). EMA republishes
                         about weekly.
  eu_union_register      Commission decisions page — no watermark of its own,
                         only our download time + decision count. Optional.
  ema_epar_documents     EMA EPAR document list JSON (the clock of the EU label
                         corpus) — meta.timestamp as stored in smpc-index.json
                         (emaList). Regenerated by EMA 06:00/18:00 Amsterdam;
                         read by our weekly label job.
  openfda_drugsfda       Drugs@FDA via openFDA — meta.last_updated recorded by
                         build-us-recent.py. Compared with CDER's novel-drug
                         roster and the FDA press-release feed: if those list
                         approvals newer than openFDA's newest original
                         approval, openFDA is LAGGING (not broken) — the app's
                         Recent-Approvals overlay already bridges that gap.
  openfda_drug_label     US prescribing information via openFDA — date openFDA
                         was last read (uspi-index.json.generated). Weekly job.
  fda_novel_roster       CDER "Novel Drug Approvals" export (manual xlsx) —
                         newest approval date in novel-approvals.json.
  fda_announcements      FDA press-release mirror (announcements.json) — fetch
                         date + newest item. Daily.
  fda_cber_cgt           CBER cell & gene therapy list — manual snapshot,
                         newest approval date (cgt-products.json).
  fda_cdx_list           FDA companion-diagnostics list — its own list date.

  With --probe the script also asks the live sources for their CURRENT
  watermark (openFDA meta.last_updated with limit=1; HTTP Last-Modified of
  EMA's xlsx and document list), so "our copy is behind the source" can be told
  apart from "the source itself has stopped". A failed probe is noted, never
  fatal — network hiccups must not block a release.

OUTPUT
  --json FILE   the full report (committed as frontend/freshness.json, so the
                next run has a previous watermark to compare with, and archived
                per release as data-releases/<id>.freshness.json)
  --md FILE     Markdown summary for the GitHub run summary
  $GITHUB_OUTPUT gets status=OK|STALE|FAILED
  exit 1 on FAILED (unless --no-fail), 0 otherwise

  python3 scripts/source-freshness.py [--probe] [--previous FILE] [--json FILE] [--md FILE] [--today YYYY-MM-DD]

Only python3 stdlib.
"""
import argparse
import datetime as dt
import json
import os
import subprocess
import sys
import urllib.request
from email.utils import parsedate_to_datetime

HERE = os.path.dirname(os.path.abspath(__file__))
FRONTEND = os.path.dirname(HERE)
REPO = os.path.dirname(FRONTEND)

OK, STALE, FAILED = 'OK', 'STALE', 'FAILED'
RANK = {OK: 0, STALE: 1, FAILED: 2}

EMA_XLSX = 'https://www.ema.europa.eu/en/documents/report/medicines-output-medicines-report_en.xlsx'
EMA_DOCS = 'https://www.ema.europa.eu/en/documents/report/documents-output-epar_documents_json-report_en.json'
OPENFDA_DRUGSFDA = 'https://api.fda.gov/drug/drugsfda.json?limit=1'
OPENFDA_LABEL = 'https://api.fda.gov/drug/label.json?limit=1'

# Thresholds in DAYS unless the name says hours. "ours" = age of OUR copy /
# download; "upstream" = age of the source's own watermark; "lag" = how far our
# copy may trail the live source (from a probe) before it counts as stale.
LIMITS = {
    'ema_medicines_report': {'ours_stale': 1.5, 'upstream_stale': 10, 'upstream_fail': 21, 'lag_stale': 2, 'collapse': 0.95},
    'eu_union_register': {'ours_stale': 1.5, 'collapse': 0.5},
    'ema_epar_documents': {'ours_stale': 9, 'ours_fail': 16, 'upstream_stale_h': 36, 'collapse': 0.95},
    # lag_stale 1.5 d: openFDA refreshes during the US day, our job runs 06:17 UTC —
    # a dataset one day newer than our copy is the normal daily rhythm, not a lag.
    'openfda_drugsfda': {'ours_stale': 1.5, 'upstream_stale': 14, 'lag_stale': 1.5, 'collapse': 0.7, 'overlay_stale': 14},
    'openfda_drug_label': {'ours_stale': 9, 'ours_fail': 16, 'collapse': 0.95},
    'fda_novel_roster': {'upstream_stale': 45},
    'fda_announcements': {'ours_stale': 1.5, 'upstream_stale': 30, 'collapse': 0.3},
    'fda_cber_cgt': {'upstream_stale': 120, 'collapse': 1.0},
    'fda_cdx_list': {'upstream_stale': 180, 'collapse': 0.95},
}


# ---------------------------------------------------------------- helpers ---
def read_json(path):
    try:
        with open(path, encoding='utf-8') as f:
            return json.load(f)
    except Exception:  # noqa: BLE001
        return None


def parse_ts(s):
    """'2026-10-07', '20261007', '2026-10-07T06:10:00Z', '+00:00', or naive ISO → aware UTC datetime."""
    if not s or not isinstance(s, str):
        return None
    s = s.strip()
    try:
        if len(s) == 8 and s.isdigit():
            return dt.datetime(int(s[:4]), int(s[4:6]), int(s[6:8]), tzinfo=dt.timezone.utc)
        if len(s) == 10:
            return dt.datetime.fromisoformat(s).replace(tzinfo=dt.timezone.utc)
        d = dt.datetime.fromisoformat(s.replace('Z', '+00:00'))
        return d if d.tzinfo else d.replace(tzinfo=dt.timezone.utc)
    except ValueError:
        return None


def iso(d):
    return d.astimezone(dt.timezone.utc).isoformat(timespec='seconds').replace('+00:00', 'Z') if d else None


def day(s):
    d = parse_ts(s)
    return d.date().isoformat() if d else None


def age_days(ts, now):
    d = parse_ts(ts) if isinstance(ts, str) else ts
    return round((now - d).total_seconds() / 86400, 2) if d else None


def fmt_age(days):
    if days is None:
        return '?'
    if days < 1:
        return f'{days * 24:.0f} h'
    return f'{days:.0f} d'


def probe(url, method='GET', timeout=30):
    """Live watermark of a source. Returns {'value': ISO, 'kind': ...} or {'error': ...}."""
    req = urllib.request.Request(url, method=method, headers={'User-Agent': 'DrugRadar-freshness'})
    for attempt in (1, 2):
        try:
            with urllib.request.urlopen(req, timeout=timeout) as r:
                if method == 'HEAD':
                    lm = r.headers.get('Last-Modified')
                    d = parsedate_to_datetime(lm) if lm else None
                    return {'value': iso(d), 'kind': 'Last-Modified'} if d else {'error': 'no Last-Modified header'}
                body = json.loads(r.read().decode('utf-8'))
                lu = (body.get('meta') or {}).get('last_updated')
                return {'value': lu, 'kind': 'meta.last_updated'} if lu else {'error': 'no meta.last_updated'}
        except Exception as e:  # noqa: BLE001
            err = f'{type(e).__name__}: {e}'[:120]
            if attempt == 2:
                return {'error': err}
    return {'error': 'unreachable'}


def previous_report(path):
    if path:
        return read_json(path)
    try:  # default: the committed report of the last run
        out = subprocess.run(['git', 'show', 'HEAD:frontend/freshness.json'], cwd=REPO, capture_output=True, text=True, check=True).stdout
        return json.loads(out)
    except Exception:  # noqa: BLE001
        return None


class Source:
    def __init__(self, key, name, cadence):
        self.key, self.name, self.cadence = key, name, cadence
        self.status, self.notes = OK, []
        self.fields = {}

    def set(self, **kw):
        self.fields.update({k: v for k, v in kw.items()})

    def mark(self, status, note):
        if RANK[status] > RANK[self.status]:
            self.status = status
        self.notes.append(note)

    def as_dict(self):
        return {'name': self.name, 'cadence': self.cadence, 'status': self.status, **self.fields, 'notes': self.notes}


# ---------------------------------------------------------------- checks ----
def check_against_previous(src, prev, count_key='count', watermark_key='sourceUpdatedAt'):
    """Watermark must never move backwards, counts must never collapse."""
    if not prev:
        return
    lim = LIMITS[src.key]
    cur_w, prev_w = src.fields.get(watermark_key), prev.get(watermark_key)
    if cur_w and prev_w and parse_ts(cur_w) and parse_ts(prev_w) and parse_ts(cur_w) < parse_ts(prev_w):
        src.mark(FAILED, f'watermark moved backwards: {prev_w} → {cur_w}')
    cur_c, prev_c = src.fields.get(count_key), prev.get(count_key)
    if isinstance(cur_c, (int, float)) and isinstance(prev_c, (int, float)) and prev_c > 0 and cur_c < lim.get('collapse', 0.9) * prev_c:
        src.mark(FAILED, f'count collapsed: {prev_c} → {cur_c}')


def check_ours(src, fetched_at, now):
    lim = LIMITS[src.key]
    age = age_days(fetched_at, now)
    src.set(fetchedAt=fetched_at, fetchedAgeDays=age)
    if age is None:
        src.mark(STALE, 'no download time recorded')
    elif 'ours_fail' in lim and age > lim['ours_fail']:
        src.mark(FAILED, f'our copy is {fmt_age(age)} old (limit {lim["ours_fail"]} d) — two refresh cycles missed')
    elif 'ours_stale' in lim and age > lim['ours_stale']:
        src.mark(STALE, f'our copy is {fmt_age(age)} old (expected within {lim["ours_stale"]} d)')


def check_upstream(src, watermark, now):
    lim = LIMITS[src.key]
    age = age_days(watermark, now)
    src.set(sourceUpdatedAt=watermark, sourceAgeDays=age)
    if age is None:
        src.mark(STALE, 'source carries no usable watermark')
        return
    if 'upstream_fail' in lim and age > lim['upstream_fail']:
        src.mark(FAILED, f'source data is {fmt_age(age)} old (limit {lim["upstream_fail"]} d) — the feed has stopped')
    elif 'upstream_stale' in lim and age > lim['upstream_stale']:
        src.mark(STALE, f'source data is {fmt_age(age)} old (normal cadence: {src.cadence})')


def check_probe(src, result, now, our_watermark=None, slack_days=0.0, stale_hours=None):
    """Live watermark vs ours: is the SOURCE stalled, or is OUR COPY behind it?"""
    if not result:
        return
    src.set(probe=result)
    if 'error' in result:
        src.notes.append(f'live probe failed: {result["error"]} (not counted)')
        return
    live = parse_ts(result['value'])
    if not live:
        return
    if stale_hours is not None:
        h = (now - live).total_seconds() / 3600
        if h > stale_hours:
            src.mark(STALE, f'source not regenerated for {h:.0f} h (expected every {stale_hours // 2:.0f} h)')
    ours = parse_ts(our_watermark) if our_watermark else None
    if ours and live > ours + dt.timedelta(days=slack_days):
        src.mark(STALE, f'source has newer data ({day(result["value"])}) than our copy ({day(our_watermark)})')


# ---------------------------------------------------------------- main ------
def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--frontend', default=FRONTEND)
    ap.add_argument('--probe', action='store_true', help='ask the live sources for their current watermark')
    ap.add_argument('--previous', help='previous freshness.json (default: HEAD:frontend/freshness.json)')
    ap.add_argument('--json', help='write the report here')
    ap.add_argument('--md', help='write the Markdown summary here')
    ap.add_argument('--today', help='override "now" (ISO date or timestamp), for tests')
    ap.add_argument('--no-fail', action='store_true', help='exit 0 even on FAILED')
    a = ap.parse_args()

    fe = a.frontend
    now = parse_ts(a.today) if a.today else dt.datetime.now(dt.timezone.utc)
    if a.today and len(a.today) == 10:
        now = now.replace(hour=12)  # a plain date means "mid-day", not midnight
    prev = previous_report(a.previous) or {}
    prev_src = prev.get('sources') or {}

    ledger = read_json(os.path.join(fe, 'scripts', '.sources.json')) or {}
    ema = read_json(os.path.join(fe, 'ema-medicines.json')) or {}
    smpc_idx = read_json(os.path.join(fe, 'smpc-index.json')) or {}
    uspi_idx = read_json(os.path.join(fe, 'uspi-index.json')) or {}
    us_recent = read_json(os.path.join(fe, 'us-recent.json')) or {}
    novel = read_json(os.path.join(fe, 'novel-approvals.json')) or {}
    ann = read_json(os.path.join(fe, 'announcements.json')) or {}
    cgt = read_json(os.path.join(fe, 'cgt-products.json')) or {}
    cdx = read_json(os.path.join(fe, 'fda-cdx.json')) or {}

    probes = {}
    if a.probe:
        probes = {
            'ema_xlsx': probe(EMA_XLSX, 'HEAD'),
            'ema_docs': probe(EMA_DOCS, 'HEAD'),
            'drugsfda': probe(OPENFDA_DRUGSFDA),
            'label': probe(OPENFDA_LABEL),
        }

    sources = []

    # --- EMA medicines report (EU catalogue) --------------------------------
    s = Source('ema_medicines_report', 'EMA medicines report (EU catalogue)', 'about weekly')
    x = ledger.get('emaXlsx') or {}
    # The ledger describes the xlsx of ITS run; only trust it for this catalogue.
    ledger_matches = bool(ledger.get('emaReportGenerated')) and ledger.get('emaReportGenerated') == ema.get('generated')
    s.set(count=len(ema.get('authorised') or []), pending=len(ema.get('pipeline') or []),
          sha256=x.get('sha256') if ledger_matches else None, url=EMA_XLSX)
    if not ema.get('generated'):
        s.mark(FAILED, 'ema-medicines.json unreadable or without a report date')
    else:
        check_upstream(s, ema.get('generated'), now)
    if ledger_matches:
        check_ours(s, x.get('retrievedAt'), now)
    else:  # local run without the CI ledger: the report date above is still the truth
        s.set(fetchedAt=None, fetchedAgeDays=None)
        s.notes.append('download ledger (scripts/.sources.json) is from another run — download time not graded')
    check_probe(s, probes.get('ema_xlsx'), now, our_watermark=ema.get('generated'), slack_days=LIMITS[s.key]['lag_stale'])
    check_against_previous(s, prev_src.get(s.key))
    sources.append(s)

    # --- EU Union Register (optional cross-check) ---------------------------
    s = Source('eu_union_register', 'EU Union Register (Commission decisions)', 'daily download, no own watermark')
    x = ledger.get('euRegister') or {}
    s.set(count=ledger.get('euRegisterDecisions'), sha256=x.get('sha256') if ledger_matches else None, sourceUpdatedAt=None)
    if not ledger_matches:
        s.set(fetchedAt=None, fetchedAgeDays=None)
        s.notes.append('download ledger is from another run — not graded')
    elif x.get('retrievedAt'):
        check_ours(s, x.get('retrievedAt'), now)
    else:
        s.mark(STALE, 'not downloaded in the last run (pending list not cross-checked)')
    check_against_previous(s, prev_src.get(s.key))
    sources.append(s)

    # --- EMA EPAR document list (EU label corpus clock) ---------------------
    s = Source('ema_epar_documents', 'EMA EPAR document list (EU labels)', 'EMA 06:00/18:00 Amsterdam; read weekly (Mondays)')
    s.set(count=smpc_idx.get('count'), url=EMA_DOCS, incomplete=smpc_idx.get('incomplete') or None)
    # The list's own timestamp is the watermark; the index date is when we read
    # it. Graded by OUR weekly cadence (EMA's twice-daily clock is probed below).
    watermark = smpc_idx.get('emaList') or smpc_idx.get('generated')
    age = age_days(watermark, now)
    s.set(sourceUpdatedAt=watermark, sourceAgeDays=age)
    lim = LIMITS[s.key]
    if age is None:
        s.mark(FAILED, 'smpc-index.json unreadable or without a date')
    elif age > lim['ours_fail']:
        s.mark(FAILED, f'EU label corpus is {fmt_age(age)} behind EMA\'s list (limit {lim["ours_fail"]} d) — two weekly runs missed')
    elif age is not None and age > lim['ours_stale']:
        s.mark(STALE, f'EU label corpus is {fmt_age(age)} old (weekly job expected within {lim["ours_stale"]} d)')
    if smpc_idx.get('incomplete'):
        inc = smpc_idx['incomplete']
        s.mark(STALE, f'last label run incomplete: {inc.get("reason", "?")}, {inc.get("unchecked", "?")} unchecked')
    s.set(fetchedAt=smpc_idx.get('generated'))
    check_probe(s, probes.get('ema_docs'), now, stale_hours=lim['upstream_stale_h'])
    check_against_previous(s, prev_src.get(s.key))
    sources.append(s)

    # --- openFDA Drugs@FDA (US recent approvals) ----------------------------
    s = Source('openfda_drugsfda', 'openFDA Drugs@FDA (US approvals)', 'openFDA: weekly dataset refresh')
    src = us_recent.get('source') or {}
    items = us_recent.get('items') or []
    newest = items[0].get('orig') if items else None
    s.set(count=src.get('records'), approvals=len(items), newestOriginalApproval=day(newest), sha256=src.get('sha256'), url=src.get('url'))
    if not src.get('openfdaLastUpdated'):
        s.mark(FAILED, 'us-recent.json carries no openFDA watermark')
    else:
        check_upstream(s, src.get('openfdaLastUpdated'), now)
    check_ours(s, src.get('retrievedAt'), now)
    check_probe(s, probes.get('drugsfda'), now, our_watermark=src.get('openfdaLastUpdated'), slack_days=LIMITS[s.key]['lag_stale'])
    # Independent reference: approvals FDA itself has announced. Newer than
    # openFDA's newest original approval → openFDA lags, the overlay serves.
    novel_dates = sorted((r.get('approvalDate') for yr in novel.values() if isinstance(yr, list) for r in yr if r.get('approvalDate')), reverse=True)
    ann_dates = sorted((r.get('date') for r in (ann.get('items') or []) if r.get('date')), reverse=True)
    ref = max([d for d in (novel_dates[:1] + ann_dates[:1]) if d], default=None)
    if ref and newest and day(newest) and ref > day(newest):
        lag = (parse_ts(ref) - parse_ts(newest)).days
        s.set(lag={'behindDays': lag, 'reference': ref, 'referenceSource': 'CDER novel roster / FDA press releases'})
        note = f'openFDA lagging: FDA announced approvals through {ref}, Drugs@FDA newest original approval {day(newest)} ({lag} d) — served by the Recent-Approvals overlay'
        s.mark(STALE if lag > LIMITS[s.key]['overlay_stale'] else OK, note)
    else:
        s.set(lag=None)
    check_against_previous(s, prev_src.get(s.key))
    sources.append(s)

    # --- openFDA drug label (US prescribing information) --------------------
    s = Source('openfda_drug_label', 'openFDA drug label (US labels)', 'openFDA: weekly; read weekly (Mondays)')
    s.set(count=uspi_idx.get('count'), url=OPENFDA_LABEL.split('?')[0])
    gen = uspi_idx.get('generated')
    s.set(sourceUpdatedAt=gen, fetchedAt=gen, sourceAgeDays=age_days(gen, now))
    age = age_days(gen, now)
    lim = LIMITS[s.key]
    if age is None:
        s.mark(FAILED, 'uspi-index.json unreadable or without a date')
    elif age > lim['ours_fail']:
        s.mark(FAILED, f'US label corpus is {fmt_age(age)} old (limit {lim["ours_fail"]} d) — two weekly runs missed')
    elif age > lim['ours_stale']:
        s.mark(STALE, f'US label corpus is {fmt_age(age)} old (weekly job expected within {lim["ours_stale"]} d)')
    check_probe(s, probes.get('label'), now)  # recorded; our weekly cadence is graded above
    check_against_previous(s, prev_src.get(s.key))
    sources.append(s)

    # --- CDER novel-drug roster (manual export) -----------------------------
    s = Source('fda_novel_roster', 'FDA CDER novel drug approvals (roster)', 'FDA: within days of each approval; manual xlsx export')
    s.set(count=sum(len(v) for v in novel.values() if isinstance(v, list)), fetchedAt=None)
    if novel_dates:
        check_upstream(s, novel_dates[0], now)
    else:
        s.mark(FAILED, 'novel-approvals.json empty or unreadable')
    if s.status == STALE:
        s.notes.append('export the current year from fda.gov → scripts/data/novel-<year>.xlsx, run build-novel-approvals.py')
    check_against_previous(s, prev_src.get(s.key))
    sources.append(s)

    # --- FDA press-release mirror -------------------------------------------
    s = Source('fda_announcements', 'FDA press releases (announcements feed)', 'daily')
    s.set(count=len(ann.get('items') or []))
    check_ours(s, ann.get('generated'), now)
    if ann_dates:
        check_upstream(s, ann_dates[0], now)
    else:
        s.mark(STALE, 'no announcements in the feed')
    check_against_previous(s, prev_src.get(s.key))
    sources.append(s)

    # --- CBER cell & gene therapies (manual snapshot) -----------------------
    s = Source('fda_cber_cgt', 'FDA CBER cell & gene therapy list', 'FDA: every few weeks; manual snapshot')
    dates = sorted((v.get('d') for v in cgt.values() if isinstance(v, dict) and v.get('d')), reverse=True)
    s.set(count=len(cgt), fetchedAt=None)
    if dates:
        check_upstream(s, dates[0], now)
    else:
        s.mark(FAILED, 'cgt-products.json empty or unreadable')
    if s.status == STALE:
        s.notes.append('compare the FDA CBER list with cgt-products.json and add what is missing (build-cgt-data.py)')
    check_against_previous(s, prev_src.get(s.key))
    sources.append(s)

    # --- FDA companion diagnostics list -------------------------------------
    s = Source('fda_cdx_list', 'FDA companion diagnostics list', 'FDA: every few months')
    s.set(count=cdx.get('total'), fetchedAt=cdx.get('generated'))
    if cdx.get('listDate'):
        check_upstream(s, cdx.get('listDate'), now)
    else:
        s.mark(STALE, 'fda-cdx.json carries no list date')
    check_against_previous(s, prev_src.get(s.key))
    sources.append(s)

    # --- Roll-up --------------------------------------------------------------
    overall = OK
    for s in sources:
        if RANK[s.status] > RANK[overall]:
            overall = s.status
    by_key = {s.key: s for s in sources}
    current_through = {
        # EU catalogue: EMA's own report date — not the day we downloaded it.
        'euCatalogue': day(ema.get('generated')),
        # EU label texts: the clock of EMA's document list we last matched against.
        'euLabels': day(smpc_idx.get('emaList') or smpc_idx.get('generated')),
        # US approvals: the openFDA dataset date; plus FDA's own announcements.
        'usApprovals': day((us_recent.get('source') or {}).get('openfdaLastUpdated')),
        'usApprovalsAnnounced': ref,
        'usLabels': day(uspi_idx.get('generated')),
        'pipelineRun': iso(now),
    }
    report = {
        'checkedAt': iso(now),
        'status': overall,
        'probed': bool(a.probe),
        'currentThrough': current_through,
        'sources': {s.key: s.as_dict() for s in sources},
        'previousCheckedAt': prev.get('checkedAt'),
    }

    # --- Markdown summary -------------------------------------------------------
    icon = {OK: '🟢', STALE: '🟡', FAILED: '🔴'}
    md = [f'## Source freshness — {now.date().isoformat()} — **{overall}**', '',
          f'EU catalogue through **{current_through["euCatalogue"]}** · EU labels through **{current_through["euLabels"]}** · '
          f'US approvals (openFDA) through **{current_through["usApprovals"]}**'
          + (f', announced through **{ref}**' if ref else '') + f' · US labels through **{current_through["usLabels"]}**', '',
          '| source | status | source data as of | age | our copy | records | notes |', '|---|---|---|---|---|---|---|']
    for s in sources:
        f = s.fields
        md.append(f'| {s.name} | {icon[s.status]} {s.status} | {day(f.get("sourceUpdatedAt")) or "—"} | {fmt_age(f.get("sourceAgeDays"))} | '
                  f'{day(f.get("fetchedAt")) or "—"} | {f.get("count") if f.get("count") is not None else "—"} | {"; ".join(s.notes) or "—"} |')
    if a.probe:
        md += ['', 'Live probes: ' + ', '.join(f'{k} = {v.get("value") or "ERR " + v.get("error", "")}' for k, v in probes.items())]
    if prev.get('checkedAt'):
        md += ['', f'Compared with the previous report of {prev["checkedAt"]} (watermark regression / count collapse → FAILED).']
    text = '\n'.join(md) + '\n'

    if a.json:
        with open(a.json, 'w', encoding='utf-8') as f:
            json.dump(report, f, indent=1, ensure_ascii=False)
            f.write('\n')
    if a.md:
        with open(a.md, 'w', encoding='utf-8') as f:
            f.write(text)
    gh = os.environ.get('GITHUB_OUTPUT')
    if gh and os.path.isdir(os.path.dirname(gh)):
        with open(gh, 'a', encoding='utf-8') as f:
            f.write(f'status={overall}\n')
    print(text)
    sys.exit(1 if overall == FAILED and not a.no_fail else 0)


if __name__ == '__main__':
    main()
