// EMA's EPAR document list — one machine-readable file, regenerated by EMA
// twice a day (06:00 / 18:00 Amsterdam), that names every EPAR document with
// its URL and `last_updated_date`. For the SmPC corpus it answers two
// questions without touching EMA's rate-limited PDF server once per label:
//   * which product-information PDF belongs to a medicine (the URL does not
//     always follow the "<slug>-epar-product-information_en.pdf" pattern:
//     arikayce-liposomal, byannl → byannli …), and
//   * whether EMA has updated it since our extract was made.
// Used by extract-all.mjs (weekly changed-only refresh) and drift-report.mjs.
import { execFileSync } from 'node:child_process';
import { readFileSync, existsSync, statSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

export const FEED_URL =
  'https://www.ema.europa.eu/en/documents/report/documents-output-epar_documents_json-report_en.json';
const PDF_SLUG = /\/en\/documents\/product-information\/(.+?)(?:-epar)?-product-information_en\.pdf$/;

const day = (s) => String(s || '').slice(0, 10);
const nextDay = (d) => (d ? new Date(Date.parse(d) + 864e5).toISOString().slice(0, 10) : '');

// slugOf() of extract-all.mjs, for records of ema-medicines.json
export const slugOf = (m) => ((m.url || '').split('/EPAR/')[1]?.trim() || '').replace(/-previously-.*$/, '');

/**
 * Downloads (or reuses a copy younger than 6 h in cacheDir) and indexes the
 * list. Returns { lookup(m) → {url, updated} | null, timestamp, size } or null
 * when the list is unavailable or implausible — callers then fall back to
 * asking EMA's PDF server directly.
 */
export function loadFeed(cacheDir, medicines = []) {
  mkdirSync(cacheDir, { recursive: true });
  const file = join(cacheDir, 'epar-documents.json');
  const fresh = existsSync(file) && Date.now() - statSync(file).mtimeMs < 6 * 36e5;
  if (!fresh) {
    try {
      execFileSync('curl', ['-fsSL', '-A', 'Mozilla/5.0', '--max-time', '300', '--retry', '2', '-o', file, FEED_URL], { stdio: 'ignore' });
    } catch {
      console.log('WARN: EMA EPAR document list unavailable — falling back to per-label checks');
      return null;
    }
  }
  let rows, meta;
  try { const j = JSON.parse(readFileSync(file, 'utf8')); rows = Array.isArray(j) ? j : j.data; meta = j.meta || {}; } catch { rows = null; }
  if (!Array.isArray(rows)) { console.log('WARN: EMA EPAR document list unreadable — falling back to per-label checks'); return null; }

  const byNum = new Map(), bySlug = new Map();
  for (const r of rows) {
    if (r?.type !== 'product-information' || !r.last_updated_date) continue;
    const url = String(r.document_url || '');
    const m = PDF_SLUG.exec(url);
    if (!m) continue;                                   // e.g. the member-state URL spreadsheet
    const hit = { url, updated: r.last_updated_date };
    const num = String(r.ema_product_number || '').split('/').slice(0, 4).join('/').toUpperCase();
    if (num) byNum.set(num, hit);
    bySlug.set(m[1], hit);
  }
  // EMA product number first (exact), else the PDF name (older snapshots carry no number).
  const lookup = (med) => (med.num && byNum.get(med.num)) || bySlug.get(slugOf(med)) || null;

  const found = medicines.filter((med) => lookup(med)).length;
  if (bySlug.size < 1000 || (medicines.length && found < 0.9 * medicines.length)) {
    console.log(`WARN: EMA EPAR document list implausible (${bySlug.size} labels, ${found}/${medicines.length} medicines found) — falling back to per-label checks`);
    return null;
  }
  return { lookup, timestamp: meta.timestamp || null, size: bySlug.size, found };
}

/**
 * Has EMA updated the product information since our extract (prev) was made?
 * Exact once an extract carries emaUpdated (the list's own clock). Older
 * extracts only know when the PDF was downloaded (retrieved) and the PDF's
 * HTTP Last-Modified (sourceModified, a different clock that can trail the
 * list by a day — one day of slack there).
 */
export function feedNewer(updated, prev) {
  if (!updated || !prev) return false;
  if (prev.emaUpdated) return updated > prev.emaUpdated;
  const base = [nextDay(day(prev.sourceModified)), day(prev.retrieved)].sort().pop();
  return day(updated) > base;
}

export const daysSince = (iso, today = new Date()) => Math.floor((today - Date.parse(day(iso))) / 864e5);
export { day };
